CREATE DATABASE BDCursosCapacitando
GO

USE BDCursosCapacitando
GO

CREATE TABLE tblTEMa(
	intCod_TEM INT IDENTITY PRIMARY KEY NOT NULL,
	strNombre_TEM VARCHAR(50) NOT NULL,
	strDescripcion_TEM VARCHAR(800) NOT NULL
	)
GO

CREATE TABLE tblCARgo(
	intCod_CAR INT IDENTITY PRIMARY KEY NOT NULL,
	strDescripcion_TEM VARCHAR(800) NOT NULL
	)
GO

CREATE TABLE tblForma_PAGo(
	intCod_FPAG INT IDENTITY PRIMARY KEY NOT NULL,
	strDescripcion_FPAG VARCHAR(800) NOT NULL
	)
GO

CREATE TABLE tblForma_PAGo(
	intCod_FPAG INT IDENTITY PRIMARY KEY NOT NULL,
	strDescripcion_FPAG VARCHAR(800) NOT NULL
	)
GOCREATE TABLE tblForma_PAGo(
	intCod_FPAG INT IDENTITY PRIMARY KEY NOT NULL,
	strDescripcion_FPAG VARCHAR(800) NOT NULL
	)
GO